name: java_setup
description: Action to setup java

inputs:
  java_version:
    description: 'Java Version'
    default: '21'
    required: true
    type: string
  java_distribution:
    description: 'Java Distribution'
    #default: 'temurin'
    default: 'oracle'
    required: true
    #type: string
    type: choice
    options:
    - temurin
    - oracle
    - zulu
    - liberica
    - corretto

#env:
#  runs:
#    using: 'node24'
#    main: 'main.js'

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{inputs.java_version}}
      uses: actions/setup-java@v5
      with:
        #java-version: '21'
        #distribution: 'temurin'
        java-version: '${{inputs.java_version}}'
        distribution: '${{inputs.java_distribution}}'
        java-package: jdk
