name: Build Setup Test
description: Builds the repository and optionally releases the given version

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        default: 'test'
        required: true
        type: choice
        options:
        - test
        - release
      version:
        description: 'Version number'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - id: setup
        uses: ./.github/actions/java_setup_action
        with:
          java_version: 25
      - run: |
          echo "Build Type: $BUILD_TYPE"
          echo "Version: $VERSION"
        env:
          BUILD_TYPE: ${{ inputs.build_type }}
          VERSION: ${{ inputs.version }}
      - name: create obj
        run: mkdir -p ./obj
      - name: clean obj
        run: rm -rf ./obj/*
      - name: compile
        run: javac --version
      - name: make jar
        run: echo "jar creation goes here"


